### ISSUE TITLE
Is it possible to change the default of Target repository to branch?

### ISSUE THREAD

**Issue by imjuanleonard** [benmatselby/hugo-deploy-gh-pages#31]
To avoid getting infinity loop between the publishing to master and deploying the github pages because there is a master branch push

**Comment by benmatselby** [comment]
Hey @imjuanleonard Could you provide a little more context please?

**Comment by imjuanleonard** [comment]
https://github.com/benmatselby/hugo-deploy-gh-pages/blob/master/action.sh#L69

Currently, the options are just for publishing to the master branch.
Can I have a place where I can specify which branch I want to push to and the default will go to master?

I can raise a PR for this if you don't mind

Thank you

**Comment by benmatselby** [comment]
> I can raise a PR for this if you don't mind
> 
> Thank you

If you have time, that's great, thank you.

**Comment by imjuanleonard** [comment]
Thanks @benmatselby 
Have raised the PR 
https://github.com/benmatselby/hugo-deploy-gh-pages/pull/32

**Comment by benmatselby** [comment]
Thank you. It may be a few days before I get time to test this, but I'll get to it, thanks once again.

**Comment by imjuanleonard** [comment]
Thanks 🙇

**Comment by benmatselby** [comment]
This is now merged, thanks @imjuanleonard
