### ISSUE TITLE
Suggest do not use git diff

### ISSUE THREAD

**Issue by tcitry** [benmatselby/hugo-deploy-gh-pages#4]
Refer to your code
https://github.com/benmatselby/hugo-deploy-gh-pages/blob/master/action.sh#L52
![image](https://user-images.githubusercontent.com/5220740/55218294-a4541500-523c-11e9-88ca-8626420ca8c1.png)

When I add new post or new image and run `hugo`, new file generated to public/, but it is not  existed in target_repo(build/), so `git diff --exist-code` can not diff anything and exit with 0.

In my opinion, don't clone the target_repo, directly run
```
cd ${GITHUB_WORKSPACK}
hugo
rm -rf .git
cd public
git init
git add .
git commit -m 'Auto build'
git remote add origin $TARGET_REPO
git push -f origin master
```
if nothing to commit, git will exit itself. and the code in public has not worthy to keep in git

**Comment by benmatselby** [comment]
Apologies @tcitry I totally missed this issue.. I'm aware of it now, thank you for raising this.
