### ISSUE TITLE
Hugo's 'publishDir' prevents the Action to complete

### ISSUE THREAD

**Issue by brunoaugusto** [benmatselby/hugo-deploy-gh-pages#43]
I met this method of auto-publishing a few months ago and, back then, I tested it with a makeshift project using the most basic theme I've found on the Internet.

Then I kept on my project, developing my own theme 'til today, release day, the action failed several times in a row pointing me with the error `/usr/bin/action.sh: line 83: cd: public: No such file or directory` right after Hugo's compilation summary (number of pages, static files, time taken...)

I've tested many possibilities to fix this without understanding why the test repository worked and the real one didn't, 'til I decided to comment out the `publishDir` entry in my `config.yaml` that was pointing to `../some-other-folder` used while developing with Hugo Server.

I don't know if you can make the Action workaround it, maybe creating a virtual copy of the `config.yaml` in the repository and manually removing that entry, who knows, I'm just posting here so anyone else in trouble has some info on how to fix that.

Thank you for your work :D

**Comment by benmatselby** [comment]
Hey @brunoaugusto 

I _think_ it's related to:


```shell
hugo "${HUGO_ARGS}"
rm -rf .git
cd public
```

I assume that Hugo is publishing (and creating) the `public` folder. Does that sound like it relates to your issue?

**Comment by benmatselby** [comment]
@brunoaugusto I've just released v1.14.0 that allows you to specify `HUGO_PUBLISH_DIR`. I hope this revolves the issue for you.
