### ISSUE TITLE
Redundant parameters still listed as 'required' in `action.yml`

### ISSUE THREAD

**Issue by tastapod** [benmatselby/hugo-deploy-gh-pages#57]
In VS Code I am getting the following warning:

    Missing required inputs: `github_token`, `hugo_version`, `target_repo`

These have been replaced by corresponding environment variables, but [action.yml][] still has them as required inputs.

[action.yml]: /benmatselby/hugo-deploy-gh-pages/blob/af723bc113338e2d40971769410edbc8966ab417/action.yml

**Comment by benmatselby** [comment]
Thanks for raising, Daniel.. I'll take a look over the next couple of days.

**Comment by benmatselby** [comment]
@tastapod If you're happy to do so, that would be lovely. Much appreciated.

**Comment by tastapod** [comment]
I started removing the mandatory inputs and then I realised they were all redundant, so I removed the whole stanza. I tested it from my fork and it worked for my one website. I would not describe it as comprehensively tested (!) but I can't see anywhere in the `action.sh` script that uses input values.

**Comment by benmatselby** [comment]
Perfect, thanks once again, @tastapod - Very much appreciated. 

This is now [released as 2.2.0](https://github.com/benmatselby/hugo-deploy-gh-pages/releases/tag/v2.2.0) :)
